# Generated by Django 4.0.3 on 2022-12-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
